### ISSUE TITLE
Support micrometer annotations

### ISSUE THREAD

**Issue by hacst** [ebullient/quarkus-micrometer-extension#38]
`micrometer-core` contains `@Timed` and `@Counted` annotations in `io.micrometer.core.annotation` that can be used by frameworks to implement UX similar to what the equivalently named MP Metrics annotations provide in `quarkus-smallrye-metrics`.

It would be great if `quarkus-micrometer-extension` could also support these.

Imho having these annotations will make it easier for MP Metrics users to switch and will generally reduce the boilerplate for basic cases. E.g.

```java
@Timed(histogram=true, description="Cool metric")
public String checkIfPrime(long number) {
  ...
}
```

vs 

```java
private Timer checkIfPrimeTimer = Timer.builder("checkIfPrime")
  .publishPercentileHistogram()
  .description("Cool metric")
  .register(Metrics.globalRegistry);

public String checkIfPrime(long number) {
  checkIfPrimeTimer.record(() -> {
     ...
   });
}
```

**Comment by ebullient** [comment]
Going to fix this in the official extension: https://github.com/quarkusio/quarkus/issues/12343

Note the disadvantage in the above is that you don't have the ability to add other information to the result. (The @Timed annotation specifically does record information about success/fail, but given other lower-level instrumentation, that annotation isn't needed as often as you might think)
